DROP DATABASE IF EXISTS rotten_db;

CREATE DATABASE rotten_db;

USE rotten_db;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE trails (
    id INT AUTO_INCREMENT PRIMARY KEY,
    trail_name VARCHAR(100) NOT NULL,
    difficulty VARCHAR(50) NOT NULL,
    elevation_gain INT NOT NULL,
    length FLOAT NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE ratings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    rating BOOLEAN NOT NULL,
    username VARCHAR(50) NOT NULL,
    trail_name VARCHAR(100) NOT NULL,
    comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (username) REFERENCES users(username),
    FOREIGN KEY (trail_name) REFERENCES trails(trail_name)
);